### ISSUE TITLE
Controller: how get a pattern

### ISSUE THREAD

**Issue by abmcr** [matcity/micro-framework#1]
Bramus router support dynamic router as /action/\d+
How can get the variable in controller? Thank you

**Comment by matcity** [comment]
Sorry for the delay,
you define a route like this:
`$route->get('/teste/(\d+)', 'HomeController@test');`

then, in the controller you get the variable via parameter
`public function test($id)
{
    echo $id;
}`

Thank you!

**Comment by abmcr** [comment]
Thanks
